name: "avm.template.module"

on:
  workflow_call:
    inputs:
      workflowInput:
        type: string
        description: "Input from the workflow caller in JSON format"
        required: true
      moduleTestFilePaths:
        type: string
        description: "List of relative path to the module test files in JSON format"
        required: true
      psRuleModuleTestFilePaths:
        type: string
        description: "List of relative path to the PSRule module test files in JSON format"
        required: true
      modulePath:
        type: string
        description: "Relative path to the module folder"
        required: true

env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_MGMTGROUP_ID: "${{ secrets.ARM_MGMTGROUP_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  TOKEN_NAMEPREFIX: "${{ secrets.TOKEN_NAMEPREFIX }}"

jobs:
  #############################
  #   Deployment validation   #
  #############################
  job_module_deploy_validation: # Note: Please don't change this job name. It is used by the setEnvironment action to define which PS modules to install on runners.
    name: "Deploy [${{ matrix.testCases.name}}]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testCases: ${{ fromJson(inputs.moduleTestFilePaths) }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set environment
        uses: ./.github/actions/templates/avm-setEnvironment
        with:
          removeDeployment: "${{ fromJson(inputs.workflowInput).removeDeployment }}"
      - name: "Run deployment validation with test file [${{ matrix.testCases.path }}]"
        uses: ./.github/actions/templates/avm-validateModuleDeployment
        with:
          modulePath: "${{ inputs.modulePath }}"
          templateFilePath: "${{ inputs.modulePath }}/${{ matrix.testCases.path }}"
          deploymentMetadataLocation: "WestEurope"
          subscriptionId: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
          managementGroupId: "${{ secrets.ARM_MGMTGROUP_ID }}"
          removeDeployment: "${{ fromJson(inputs.workflowInput).removeDeployment }}"
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}