name: "avm.res.operational-insights.workspace"

on:
  workflow_dispatch:
  push:
    branches:
      - users/alsehr/threadingTest

env:
  modulePath: "avm/res/operational-insights/workspace"
  workflowPath: ".github/workflows/avm.res.operational-insights.workspace.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ###########################
  #   Initialize pipeline   #
  ###########################
  job_initialize_pipeline:
    runs-on: ubuntu-20.04
    name: "Initialize pipeline"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Run Pester tests"
        id: pester_run_step
        shell: pwsh
        run: |
          # Grouping task logs
          Write-Output '::group::Run Pester tests'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'staticValidation' 'compliance' 'Set-PesterGitHubOutput.ps1')

          # Set repo root path
          $repoRootPath = $env:GITHUB_WORKSPACE

          # Set test input module path
          $moduleFolderPaths = @(Join-Path $repoRootPath "${{ env.modulePath }}")
          $moduleFolderPaths += (Get-ChildItem $moduleFolderPaths -Recurse -Directory -Force).FullName | Where-Object {
            (Get-ChildItem $_ -File -Depth 0 -Include @('main.json', 'main.bicep') -Force).Count -gt 0
          }

          Write-Verbose "Module folder paths: $($moduleFolderPaths | ConvertTo-Json)" -Verbose

          $pathsToBuild = [System.Collections.ArrayList]@()
          $pathsToBuild += $moduleFolderPaths | Where-Object { $_ } | ForEach-Object { Join-Path $_ 'main.bicep' }

          try {
            $builtTestFileMap = [System.Collections.Concurrent.ConcurrentDictionary[string, object]]::new()
            $pathsToBuild | ForEach-Object -Parallel {
                try {
                  $dict = $using:builtTestFileMap
                  Write-Output "Made it past [`$dict] [$_]"
                } catch {
                  Write-Output "x Made it NOT past [`$dict] [$_]"
                  return
                }

                try {
                  bicep build $_ --stdout | ConvertFrom-Json -AsHashtable
                  # $builtTemplate = Get-Content (Join-Path (Split-Path $_) 'main.json') | ConvertFrom-Json -AsHashtable
                  $builtTemplate = 'Oi!'
                  Write-Output "Made it past [`$buildTemplate] [$_]"
                }
                catch {
                  Write-Output "x Made it NOT past [`$buildTemplate] [$_]"
                  return
                }

                try {
                  $null = $dict.TryAdd($_, $builtTemplate)
                  Write-Output "Made it past [`$null] [$_]"
                } catch {
                  Write-Output "x Made it NOT past [`$null] [$_]"
                  return
                }
            } -ThrottleLimit 1

            Write-Verbose ('Post loop 1.') -Verbose
            $builtTestFileMap
          }
          finally {
            Write-Verbose ('Post loop 2. Running [bicep build {0} --stdout]' -f $pathsToBuild[0]) -Verbose
            bicep build $pathsToBuild[-1] --stdout
            Write-Verbose ('Post loop 3.') -Verbose
          }

    #   - name: "Set input parameters to output variables"
    #     id: get-workflow-param
    #     uses: ./.github/actions/templates/avm-getWorkflowInput
    #     with:
    #       workflowPath: "${{ env.workflowPath}}"
    #   - name: "Get module test file paths"
    #     id: get-module-test-file-paths
    #     uses: ./.github/actions/templates/avm-getModuleTestFiles
    #     with:
    #       modulePath: "${{ env.modulePath }}"
    # outputs:
    #   workflowInput: ${{ steps.get-workflow-param.outputs.workflowInput }}
    #   moduleTestFilePaths: ${{ steps.get-module-test-file-paths.outputs.moduleTestFilePaths }}
    #   psRuleModuleTestFilePaths: ${{ steps.get-module-test-file-paths.outputs.psRuleModuleTestFilePaths }}
    #   modulePath: "${{ env.modulePath }}"

  # ##############################
  # #   Call reusable workflow   #
  # ##############################
  # call-workflow-passing-data:
  #   name: "Module"
  #   needs:
  #     - job_initialize_pipeline
  #   uses: ./.github/workflows/avm.template.module.yml
  #   with:
  #     workflowInput: "${{ needs.job_initialize_pipeline.outputs.workflowInput }}"
  #     moduleTestFilePaths: "${{ needs.job_initialize_pipeline.outputs.moduleTestFilePaths }}"
  #     psRuleModuleTestFilePaths: "${{ needs.job_initialize_pipeline.outputs.psRuleModuleTestFilePaths }}"
  #     modulePath: "${{ needs.job_initialize_pipeline.outputs.modulePath}}"
  #   secrets: inherit
