name: "avm.template.module"

on:
  workflow_call:
    inputs:
      workflowInput:
        type: string
        description: "Input from the workflow caller in JSON format"
        required: true
      moduleTestFilePaths:
        type: string
        description: "List of relative path to the module test files in JSON format"
        required: true
      modulePath:
        type: string
        description: "Relative path to the module folder"
        required: true
      calculatedAction:
        type: string
        description: "The pipeline action to run based on the changed files"
        required: true

permissions:
  id-token: write # For OIDC
  contents: write # For release tags

env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
  ARM_MGMTGROUP_ID: "${{ secrets.ARM_MGMTGROUP_ID }}"
  ARM_TENANT_ID: "${{ secrets.ARM_TENANT_ID }}"
  TOKEN_NAMEPREFIX: "${{ secrets.TOKEN_NAMEPREFIX }}"

jobs:
  #########################
  #   Static validation   #
  #########################
  job_module_static_validation: # Note: Please don't change this job name. It is used by the setEnvironment action to define which PS modules to install on runners.
    name: "Static validation"
    runs-on: ubuntu-20.04
    if: contains('runStaticTestsOnly runAllTests' ,'${{ inputs.calculatedAction }}')
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Set environment
      #   uses: ./.github/actions/templates/avm-setEnvironment
      # - name: "Run tests"
      #   uses: ./.github/actions/templates/avm-validateModulePester
      #   with:
      #     modulePath: "${{ inputs.modulePath }}"
    - name: Static validation
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Write-Host 'Running static validation'

          # Write-Host 'Static validation: ${{ fromJson(inputs.workflowInput).staticValidation }}'
          # Write-Host 'GH event: ${{ github.event_name }}'
          # Write-Host 'Calculated: ${{ inputs.calculatedAction }}'
          # Write-Host 'Contains: ${{ contains('runStaticTestsOnly runAllTests', github.calculatedAction) }}'

  #########################
  #   PSRule validation   #
  #########################
  job_psrule_test: # Note: Please don't change this job name. It is used by the setEnvironment action to define which PS modules to install on runners.
    name: "PSRule validation"
    runs-on: ubuntu-20.04
    # TODO: We could also consider running this only for changed deployment files?
    if: contains('runStaticTestsOnly runAllTests' ,'${{ inputs.calculatedAction }}')
    strategy:
      fail-fast: false
      matrix:
        moduleTestFilePaths: ${{ fromJson(inputs.moduleTestFilePaths) }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Set environment
      #   uses: ./.github/actions/templates/avm-setEnvironment
      # - name: Set PSRule validation
      #   uses: ./.github/actions/templates/avm-validateModulePSRule
      #   with:
      #     templateFilePath: "${{ inputs.modulePath }}/${{ matrix.moduleTestFilePaths }}"
      #     subscriptionId: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      #     managementGroupId: "${{ secrets.ARM_MGMTGROUP_ID }}"
      #     psrulePath: "avm/utilities/pipelines/staticValidation/psrule" #'${{ github.workspace }}/avm'
    - name: PSRule
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Write-Host 'Running PSRule test for [${{ matrix.moduleTestFilePaths }}]'
  #############################
  #   Deployment validation   #
  #############################
  job_module_deploy_validation: # Note: Please don't change this job name. It is used by the setEnvironment action to define which PS modules to install on runners.
    name: "Deployment validation"
    runs-on: ubuntu-20.04
    if: !cancelled() && needs.job_module_static_validation.result != 'failure' && contains('runAllTests' ,'${{ inputs.calculatedAction }}')
    needs:
      - job_module_static_validation
      # - job_psrule_test # Ignoring dependency whilst PSRule gets bedded in, in this project
    strategy:
      fail-fast: false
      matrix:
        moduleTestFilePaths: ${{ fromJson(inputs.moduleTestFilePaths) }}
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Set environment
      #   uses: ./.github/actions/templates/avm-setEnvironment
      #   with:
      #     removeDeployment: "${{ fromJson(inputs.workflowInput).removeDeployment }}"
      # - name: "Using test file [${{ matrix.moduleTestFilePaths }}]"
      #   uses: ./.github/actions/templates/avm-validateModuleDeployment
      #   with:
      #     templateFilePath: "${{ inputs.modulePath }}/${{ matrix.moduleTestFilePaths }}"
      #     location: "WestEurope"
      #     subscriptionId: "${{ secrets.ARM_SUBSCRIPTION_ID }}"
      #     managementGroupId: "${{ secrets.ARM_MGMTGROUP_ID }}"
      #     removeDeployment: "${{ fromJson(inputs.workflowInput).removeDeployment }}"
      #   env:
      #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deployment test task
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Write-Host 'Running Deployment test for [${{ matrix.moduleTestFilePaths }}]'

          Write-Host 'Deployment validation: ${{ fromJson(inputs.workflowInput).deploymentValidation }}'
          Write-Host 'GH event: ${{ github.event_name }}'
          Write-Host 'Calculated: ${{ inputs.calculatedAction }}'
          Write-Host 'Contains: ${{ contains('runAllTests', github.calculatedAction) }}'
          Write-Host 'All ${{ needs.job_module_static_validation.result != 'failure' && contains('runAllTests', github.calculatedAction) }}'
  ##################
  #   Publishing   #
  ##################
  job_publish_module: # Note: Please don't change this job name. It is used by the setEnvironment action to define which PS modules to install on runners.
    name: "Publishing"
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main' && success()
    needs:
      - job_module_static_validation
      - job_module_deploy_validation
    steps:
      # - name: "Checkout"
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Set environment
      #   uses: ./.github/actions/templates/avm-setEnvironment
      # - name: "Publishing"
      #   uses: ./.github/actions/templates/avm-publishModule
      #   with:
      #     templateFilePath: "${{ inputs.modulePath }}/main.bicep"
      #   env:
      #     PUBLISH_REGISTRY_SERVER: "${{ secrets.PUBLISH_REGISTRY_SERVER }}"
      #     PUBLISH_CLIENT_ID: "${{ secrets.PUBLISH_CLIENT_ID }}"
      #     PUBLISH_TENANT_ID: "${{ secrets.PUBLISH_TENANT_ID }}"
      #     PUBLISH_SUBSCRIPTION_ID: "${{ secrets.PUBLISH_SUBSCRIPTION_ID }}"
    - name: Publish task
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          Write-Host 'running publishing for [${{ inputs.modulePath }}]'